---
title: "Assignment9"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Book Category
```{r}
library('httr')
library(jsonlite)
library(dplyr)
url='https://api.nytimes.com/svc/books/v3/lists/overview.json?api-key=87e3145b9ace45c0aba3bc181e35426f'
df <- jsonlite::fromJSON(url, flatten = TRUE)
df$results$lists$display_name
```
## Science Books
```{r}
book<-subset(df$results$lists,display_name=='Science',select = books)[[1]]
subset(book[[1]],select=c(author,title,book_image,contributor,primary_isbn10,publisher,rank))
```
## Buy Link
```{r}
book<-subset(df$results$lists,display_name=='Science',select = books)[[1]]
link<-subset(book[[1]],select=c(title,buy_links))
r<-link$buy_links[[1]]
for (i in 2:length(link$buy_links))
r<-rbind(r,link$buy_links[[i]])
r<-arrange(r,name)
r<-cbind(link$title,r)
names(r)[names(r)=="link$title"] <- "title"
r

```
## Business
```{r}
book<-subset(df$results$lists,display_name=='Business',select = books)[[1]]
subset(book[[1]],select=c(author,title,book_image,contributor,primary_isbn10,publisher,rank))
```
```{r}
book<-subset(df$results$lists,display_name=='Business',select = books)[[1]]
link<-subset(book[[1]],select=c(title,buy_links))
r<-link$buy_links[[1]]
for (i in 2:length(link$buy_links))
r<-rbind(r,link$buy_links[[i]])
r<-arrange(r,name)
r<-cbind(link$title,r)
names(r)[names(r)=="link$title"] <- "title"
r
```